### ISSUE TITLE
Import der Verbissdaten und "Potenzialflächen" für IDW in Cloud Spatialite

### ISSUE THREAD

**Issue by twiebke** [b-lack/vwm-brandenburg#3]
Die Verbissprozente an den Stichprobenpunkten sind im Layer "ivus_verb_ob_drittel" in der Spatialite in der Cloud. Die Punkte, die als Potenzialflächen erfasst wurden sind dort mit "potenzialfl"=true und Verbissprozent=150 erfasst.

**Comment by b-lack** [comment]
Da im Layer Verbissprozent niemals mit 0% aufgenommen wurde, nehme ich erstmal an, das NULL==0 sein soll.
