### ISSUE TITLE
IDW auf H3

### ISSUE THREAD

**Issue by twiebke** [b-lack/vwm-brandenburg#4]
Vorerst brauchen wir das ja nur einmal. Mein Vorschlag daher: aus den Verbissprozenten ein IDW für Brandenburg mit 125 m (?) Kachelgröße mit den Waldflächen fg_wld_75 als Bruchkanten erzeugen und die Werte auf die in den Waldflächen vorkommenden H3-Index in Resolution 10 übertragen. 
Der Layer mit der Resolution 10 ist dann der Grundlayer für kleiner als Oberförsterei. Ab Oberförsterei werden die Werte in der Resolution 9 zusammengeführt (Mittelwertbildung?) und auf Landesebene in Resolution 8. 
Mit der Reduzierung auf die Waldfläche sollte sich die Anzahl der Indexflächen reduzieren. Das müsste dann allerdings immer noch insofern dynamisch laufen, dass immer nur die indexflächen geladen werden die auch gerade im Kartenausschnitt mit der jeweiligen Zoomstufe sind.

**Comment by b-lack** [comment]
Um nötige Performance-Test durchführen zu können ist die Auflösung 10 als erstes umgesetzt worden: 
![image](https://user-images.githubusercontent.com/11278402/135335999-c6fb8559-38bc-44fb-8b0d-fce6b9b3f094.png)

Weitere Auflösungen können generiert werden, wenn das Karten-Framework definiert ist.

**Comment by b-lack** [comment]
Das aktuelle Setup ist:

- Darstellung nutzt jetzt: https://deck.gl/docs/api-reference/geo-layers/h3-hexagon-layer . Ausprobiert wurden außerdem leaflet und openlayers.  Beides hat nicht die erwünschte Performance geliefert.
- Die Verarbeitung der Daten passiert über node. Die Performance soll höher sein als eine vergleichbare Auswertung mit python oder R. In der H3-Auflösung 10, dauert die Verarbeitung der Daten etwa 10 Minuten.
